using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace MongoDownloader
{
    /// <summary>
    /// Writes <c>src/Mongo2Go/MongoBinaries.sha256</c>, the manifest that <c>MongoBinaryManifest</c> verifies against
    /// at runtime.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This runs as the last step of a download, after extraction and stripping, so the recorded checksums are of the
    /// binaries as they are actually committed and packaged. Generating it by hand is not an option worth leaving
    /// open: a manifest that disagrees with <c>tools/</c> makes Mongo2Go reject its own binaries, and the failure
    /// would surface on a consumer's machine rather than here.
    /// </para>
    /// <para>
    /// The manifest is only meaningful because the archives it derives from were checked against MongoDB's published
    /// SHA-256 first. Without that, it would faithfully record whatever we happened to download.
    /// </para>
    /// </remarks>
    internal static class BinaryManifestWriter
    {
        private const string ManifestFileName = "MongoBinaries.sha256";

        private static readonly string[] ExecutableNames =
        {
            "mongod", "mongoimport", "mongoexport",
            "mongod.exe", "mongoimport.exe", "mongoexport.exe"
        };

        private const string StripToolPrefix = "# Stripped with: ";

        public static async Task<FileInfo> WriteAsync(DirectoryInfo toolsDirectory, string communityServerVersion, string databaseToolsVersion, string? stripToolVersion, CancellationToken cancellationToken)
        {
            var manifestFile = LocateManifestFile(toolsDirectory);
            var entries = await CollectEntriesAsync(toolsDirectory, cancellationToken);

            // When regenerating without stripping (--write-manifest), keep whatever the previous manifest recorded:
            // the binaries have not changed, so neither has the tool that produced them.
            stripToolVersion ??= ReadPreviousStripToolVersion(manifestFile);

            if (entries.Count == 0)
            {
                throw new InvalidOperationException(
                    $"No MongoDB executables were found under \"{toolsDirectory.FullName}\", so no checksum manifest " +
                    $"can be written. Refusing to overwrite \"{manifestFile.FullName}\" with an empty manifest.");
            }

            var builder = new StringBuilder();
            builder.AppendLine("# Mongo2Go - SHA-256 checksums of the bundled MongoDB binaries.");
            builder.AppendLine("#");
            builder.AppendLine("# Generated by src/MongoDownloader - do not edit by hand.");
            builder.AppendLine("# Verified at runtime by MongoBinaryManifest for binaries found through the DEFAULT");
            builder.AppendLine("# search. Binaries supplied explicitly by the caller (binariesSearchDirectory /");
            builder.AppendLine("# binariesSearchPatternOverride) are accepted without verification.");
            builder.AppendLine("#");
            builder.AppendLine($"# MongoDB Community Server {communityServerVersion} / Database Tools {databaseToolsVersion}");
            builder.AppendLine($"{StripToolPrefix}{(string.IsNullOrWhiteSpace(stripToolVersion) ? "not stripped" : stripToolVersion)}");
            builder.AppendLine("#");
            builder.AppendLine("# To reproduce these checksums: download the same MongoDB release, verify it against the");
            builder.AppendLine("# SHA-256 MongoDB publishes, then strip with the tool version recorded above.");
            builder.AppendLine();

            foreach (var entry in entries)
            {
                builder.AppendLine($"{entry.Platform}/{entry.FileName}  {entry.Checksum}");
            }

            // Written with LF regardless of host, so the file does not churn between contributors.
            await File.WriteAllTextAsync(manifestFile.FullName, builder.ToString().Replace("\r\n", "\n"), cancellationToken);
            manifestFile.Refresh();
            return manifestFile;
        }

        /// <summary>
        /// Recovers the recorded strip-tool version from an existing manifest, so regenerating without stripping does
        /// not silently discard it.
        /// </summary>
        private static string? ReadPreviousStripToolVersion(FileInfo manifestFile)
        {
            if (!manifestFile.Exists)
            {
                return null;
            }

            foreach (var line in File.ReadLines(manifestFile.FullName))
            {
                if (line.StartsWith(StripToolPrefix, StringComparison.Ordinal))
                {
                    var value = line.Substring(StripToolPrefix.Length).Trim();
                    return value.Equals("not stripped", StringComparison.OrdinalIgnoreCase) ? null : value;
                }
            }

            return null;
        }

        private static async Task<List<(string Platform, string FileName, string Checksum)>> CollectEntriesAsync(DirectoryInfo toolsDirectory, CancellationToken cancellationToken)
        {
            var entries = new List<(string Platform, string FileName, string Checksum)>();

            foreach (var executable in toolsDirectory
                         .EnumerateFiles("*", SearchOption.AllDirectories)
                         .Where(file => ExecutableNames.Contains(file.Name, StringComparer.OrdinalIgnoreCase)))
            {
                cancellationToken.ThrowIfCancellationRequested();

                var platform = PlatformOf(executable, toolsDirectory);
                if (platform == null)
                {
                    continue;
                }

                entries.Add((platform, executable.Name, await ComputeSha256Async(executable, cancellationToken)));
            }

            // Stable ordering, so an unchanged tools/ always produces a byte-identical manifest.
            return entries
                .OrderBy(e => e.Platform, StringComparer.Ordinal)
                .ThenBy(e => e.FileName, StringComparer.Ordinal)
                .ThenBy(e => e.Checksum, StringComparer.Ordinal)
                .ToList();
        }

        /// <summary>
        /// Derives the platform from the top-level directory name under <c>tools/</c>, for example
        /// <c>mongodb-linux-x64-8.0.0-database-tools-100.14.0</c>.
        /// </summary>
        private static string? PlatformOf(FileInfo executable, DirectoryInfo toolsDirectory)
        {
            var relative = executable.FullName.Substring(toolsDirectory.FullName.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var topLevel = relative.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).FirstOrDefault() ?? "";

            foreach (var platform in new[] { "linux", "macos", "windows" })
            {
                if (topLevel.Contains($"-{platform}-", StringComparison.OrdinalIgnoreCase))
                {
                    return platform;
                }
            }

            return null;
        }

        private static async Task<string> ComputeSha256Async(FileInfo file, CancellationToken cancellationToken)
        {
            using var sha256 = SHA256.Create();
            await using var stream = file.OpenRead();
            var hash = await sha256.ComputeHashAsync(stream, cancellationToken);
            return Convert.ToHexString(hash).ToLowerInvariant();
        }

        /// <summary>
        /// Resolves the manifest path from the tools directory, which is a sibling of <c>src/</c>.
        /// </summary>
        private static FileInfo LocateManifestFile(DirectoryInfo toolsDirectory)
        {
            var repositoryRoot = toolsDirectory.Parent
                ?? throw new InvalidOperationException($"\"{toolsDirectory.FullName}\" has no parent directory, so the repository root cannot be determined.");

            var manifestFile = new FileInfo(Path.Combine(repositoryRoot.FullName, "src", "Mongo2Go", ManifestFileName));

            if (manifestFile.Directory is null || !manifestFile.Directory.Exists)
            {
                throw new InvalidOperationException(
                    $"Expected to find the Mongo2Go project at \"{manifestFile.Directory?.FullName}\" in order to write " +
                    $"the checksum manifest, but that directory does not exist.");
            }

            return manifestFile;
        }
    }
}
