<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="bloomtom.HttpProgress" Version="2.3.2" />
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="CliWrap" Version="3.10.1" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="Spectre.Console" Version="0.55.2" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
  
</Project>
